version: "3"

services:
  api:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    container_name: rback

  client:
    build: ./frontend
    ports:
      - "3002:80"
    container_name: rfront

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: rmongo
    command: --quiet